apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sxbg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-sxbg@sha256:6821eea7370ef97dcf49e1d6108c13465cde980c15de38cca428005488d1a94e
        name: my-nodejs
        resources: {}
status: {}
